### ISSUE TITLE
Deploy to Docker Cloud button

### ISSUE THREAD

**Issue by cgarnier** [lfilho/bitbucket-slack-pr-hook#11]
Hello,
Looks great.
Could you publish a public docker image and add a docker-compose.yml file?

https://docs.docker.com/docker-cloud/feature-reference/deploy-to-cloud/

Thanks,

**Comment by lfilho** [comment]
Hey there, I am marrying and moving to another country, so I'd much appreciate a PR for the compose file. (Docker Cloud button just got implemented via the aforementioned PR).

Thank you
