### ISSUE TITLE
Notify reviewers in the slack message

### ISSUE THREAD

**Issue by gbmoretti** [lfilho/bitbucket-slack-pr-hook#13]
It would be great if the message in Slack could notify reviewers.
Bitbucket's request already sends reviewers in the payload, we could assume they have the same username in Slack and notify them via @ mention.

I could do this PR, but first I would like to hear the mantainer's opinion.

**Comment by brh55** [comment]
Assuming they have the same username, I think this would be a worthy enhancement as long it's configurable and off by default. :+1: 

@lfilho

**Comment by lfilho** [comment]
That sounds nice and I agree with @brh55 - maybe the reviewers' Slack username differs from their bitbucket username, so they wouldn't get notified as you wanted...
But even so, I think it's worth it... In the worst case each Slack user could add a "highlight word" in their preferences for their bitbucket username and then all is fine...

Hit it! :) Thanks

**Comment by lfilho** [comment]
Merged via #14. Thanks again!
