### ISSUE TITLE
Not working on Heroku

### ISSUE THREAD

**Issue by andreichenchik** [lfilho/bitbucket-slack-pr-hook#16]
It seems linke Bitbucket changed something?
I looking into logs and everything seems to be okay, but not working at all.

> Apr 19 05:18:39 titanium-pr-slack-bot app/web.1:  Receiving events for  
> Apr 19 05:18:39 titanium-pr-slack-bot app/web.1:  ip=::ffff:10.122.22.244 time=2016-04-19T12:18:38.415Z method=POST path=/slack-test status=200 request_id=13782734-4475-4e5d-b632-63bc3863f350 content_length= content_type= elapsed=1ms 
> Apr 19 05:18:39 titanium-pr-slack-bot heroku/router:  at=info method=POST path="/slack-test" host=titanium-pr-slack-bot.herokuapp.com request_id=13782734-4475-4e5d-b632-63bc3863f350 fwd="104.192.143.193" dyno=web.1 connect=0ms service=9ms status=200 bytes=117

**Comment by brh55** [comment]
I don't see any breaking changes to the bitbucket payload. It's possibly a configuration issue, I'll try to do some testing sometime this week.

**Comment by andreichenchik** [comment]
@brh55 any ideas on how can I debug it myself? Can I turn debug to view what is getting in and what is getting out? thanks!

**Comment by brh55** [comment]
@achenchik, you can log the message and verify that the SlackService is attempting to send a message.

I would start by logging out within the sendMessage function in slackService.js at line 30,
console.log(params)

Then give it a test PR to see if it's sending it to the correct configs, if so then might be associated with the slack module.

**Comment by lfilho** [comment]
I'm assuming the issue has been solved by now, so I'll go ahead and close this one. Cheers
