### ISSUE TITLE
Adapted for AWS Lambda

### ISSUE THREAD

**Issue by booleanbetrayal** [lfilho/bitbucket-slack-pr-hook#17]
Just wanted to mention that I found this project very helpful recently. I adapted the code for the Slack message transformation. I did encounter some issues with the `attachments` message body format as expected by Slack (probably due to API change on their end). We had to move fast and couldn't standup a new environment, so we decided to use AWS Lambda with its API Gateway connector. It fields requests as needed for this proxy. Here's the code (with updated formatting adherence). Thanks so much!

https://gist.github.com/booleanbetrayal/ff23c0853828944f6921f99bf249119a

**Comment by lfilho** [comment]
Thanks, @booleanbetrayal. Glad you found it helpful.
It would be great if you had some time now to submit a PR back. (Or someone else reading this thread).

Until then I'm going ahead and closing this issue just for organisation's sake 😊
