### ISSUE TITLE
node-slack changes?

### ISSUE THREAD

**Issue by t2y** [lfilho/bitbucket-slack-pr-hook#7]
I tried to use bitbucket-slack-pr-hook, but it doesn't work. I found node-slack constructor changed. Could you follow slack api changes?

* https://github.com/xoxco/node-slack/commit/a5f647f9a284633870b44c8c6a34b53d92243abc

**Comment by brh55** [comment]
I've submitted a PR for this, in addition to a few features. Also included a quick "Deploy to Heroku", which will get you running in less then a few minutes, if you are still having troubles.

**Comment by t2y** [comment]
I found your PR: https://github.com/lfilho/bitbucket-slack-pr-hook/pull/8

Sound good. I'll try.

**Comment by codejanovic** [comment]
@brh55 the changes from #8 do not work for me :-(

**Comment by brh55** [comment]
@codejanovic How are you trying to deploy the slack bot? I'm not familiar with Docker, but I'll be gladly willing to assist in deployment through Heroku.

**Comment by codejanovic** [comment]
@brh55 I configured the webhook url via heroku (SLACK_WEBHOOK) and set up the incoming webhook in Slack (there I also defined the channel & the bot name). But I also tried to define the channel & botname in heroku through the suggested SLACK_CHANNEL and SLACK_USERNAME vars

**Comment by brh55** [comment]
@codejanovic Sorry still working through this within my limited spare time. I'm able to successfully post with the slackService set up through Heroku (manual and quick deploy). However, it appears to be an issue with the incoming post from BitBucket and the generate message method in the bitbucket parser service:

```javascript
        if (!action) {
            console.log('An unknown action was submitted:', message);
            return undefined;
        }
```

**Comment by codejanovic** [comment]
@brh55 no need to sorry, thank you for ur help in advance. well, you are totally right - i did not see the "an unknown action was submitted" in the logfiles :D

**Comment by codejanovic** [comment]
@brh55 oh my ... i am sorry - just took a look into the bitbucket parser and realized that this is only a pull-request hook - i thought its a hook for everything (tickets, pushs, comments). sorry for stealing your time brandon

**Comment by brh55** [comment]
@codejanovic Haha no worries, I still need to resolve this issue regardless. :dancer:.

Looks like you might be looking for something along the lines of the bitbucket integration, which only provide push notification. However, maybe I'll attempt to implement tickets and push updates onto my fork once I resolve the issue.

**Comment by lfilho** [comment]
Seems like this issue can be closed. @brh55's changes are already in so I'm assuming any new problem is a new one... Thanks
